apiVersion: v1
kind: Service
metadata: 
    name: coupon-service  # used in app.properties
    labels: 
        app: coupon-app
spec:
    selector:
        app: coupon-app 
    type: NodePort
    ports: 
        - port: 8081
          targetPort: 8081
          nodePort: 30555