apiVersion: v1
kind: Service
metadata: 
    name: product-service
    labels: 
        app: product-app
spec:
    selector:
        app: product-app 
    type: NodePort
    ports: 
        - port: 8082
          targetPort: 8082
          nodePort: 30666