apiVersion: v1
kind: PersistentVolume
metadata:
    name: demo-persitent-volume
spec: 
    capacity: 
        storage: 128M
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: /data/demo-persitent-volume  # Where on cluster